### ISSUE TITLE
Bug found in MPU9250_EnableI2CBypass and MPU9250_DisableI2CBypass (in file MPU9250.c)

### ISSUE THREAD

**Issue by mp1994** [dado93/PSoC-Example-Projects#1]
To set (in `MPU9250_EnableI2CBypass`) or clear (in `MPU9250_DisableI2CBypass`) the bit `BYPASS_EN `[1], the correct line should be:

    temp |= 0x02;

and

    temp &= ~0x02;

respectively for the two functions (instead of `0x01`).
Also, it is required to clear/set bit 5 of the user control registrer (I2C_MST_EN) to disable/enable the master I2C module that controls the magnetometer. 

Here is the code to fix the bug.

    void MPU9250_EnableI2CBypass(void) {
        // Clear bit [5] of MPU9250_USER_CTRL_REG
        // Read current value
        uint8_t temp = MPU9250_I2C_Read(MPU9250_I2C_ADDRESS, MPU9250_USER_CTRL_REG);
        // Clear bit [5]
        temp &= ~0x20;
        // Write new value
        MPU9250_I2C_Write(MPU9250_I2C_ADDRESS, MPU9250_USER_CTRL_REG, temp);   
        
        // Set bit [1] of MPU9250_INT_PIN_CFG_REG
        // Read current value
        temp = MPU9250_I2C_Read(MPU9250_I2C_ADDRESS, MPU9250_INT_PIN_CFG_REG);
        // Set bit[1]
        temp |= 0x02;
        // Write new value
        MPU9250_I2C_Write(MPU9250_I2C_ADDRESS, MPU9250_INT_PIN_CFG_REG, temp);
        
        CyDelay(10);
        
    }

    void MPU9250_DisableI2CBypass(void) {
        // Set bit [5] of MPU9250_INT_ENABLE_REG
        // Read current value
        uint8_t temp = MPU9250_I2C_Read(MPU9250_I2C_ADDRESS, MPU9250_USER_CTRL_REG);
        // Set bit [5]
        temp |= 0x20;
        // Write new value
        MPU9250_I2C_Write(MPU9250_I2C_ADDRESS, MPU9250_USER_CTRL_REG, temp);   
        
        // Clear bit [1] of MPU9250_INT_PIN_CFG_REG
        // Read current value
        temp = MPU9250_I2C_Read(MPU9250_I2C_ADDRESS, MPU9250_INT_PIN_CFG_REG);
        // Clear bit[1]
        temp &= ~0x02;
        // Write new value
        MPU9250_I2C_Write(MPU9250_I2C_ADDRESS, MPU9250_INT_PIN_CFG_REG, temp);
    }

**Comment by dado93** [comment]
Thanks @mp1994 for informing me of this bug.

I'll fix it asap.

Davide
